#!/bin/bash

sonar-uninstall-plugins-xml-java-javascript() {

 sonar-uninstall-plugins \
 "sonar-xml" \
 "sonar-java" \
 "sonar-javascript" 

}

sonar-uninstall-plugins() { { local candidate_plugins ; candidate_plugins=${@} ; }
 
 ( 

  cd extensions/plugins 
  local plugin
  for plugin in ${candidate_plugins}
  do
   rm -rvf ${plugin}*
  done

 )

}

sonar-install-plugins-go-python-scala() {
 
 sonar-install-plugins "https://github.com/uartois/sonar-golang/releases/download/v1.2.10/sonar-golang-plugin-1.2.10.jar" "https://sonarsource.bintray.com/Distribution/sonar-python-plugin/sonar-python-plugin-1.8.0.1496.jar" "https://github.com/Sagacify/sonar-scala/releases/download/v0.0.3/sonar-scala-plugin-0.0.3.jar"

}
sonar-install-plugins() { { local candidate_plugin_urls ; candidate_plugin_urls=${@} ; }
 # Install plugins
 (
  cd extensions/plugins
  local url
  for url in ${candidate_plugin_urls}
  do
   test -f "$( basename ${url} )" || {
    wget ${url}
   }
  done
 )
}

sonar-properties-increase-heap-size() {
 sed -i -e 's/#sonar.web.javaOpts.*/sonar.web.javaOpts=-Xmx3062m -Xms128m -XX:+HeapDumpOnOutOfMemoryError/' conf/sonar.properties
}

sonar-start() {
 ## for apt-get installed sonar
 #bin/linux-x86-64/sonar.sh \
 #	start
 #tail -f opt/sonarqube/logs/sonar.log
 bin/run.sh
}

sonar-list() {
 #sonar-uninstall-plugins-xml-java-javascript
 sonar-install-plugins-go-python-scala
 sonar-properties-increase-heap-size
 sonar-start
}

sonar-list

exit 0
